import type { GameConfig } from '../core/types';
import {
  AGENT_API_VERSION,
  APP_VERSION,
  ARTIFACT_SCHEMA_VERSION,
  BRIDGE_API_VERSION,
  GAME_RULES_VERSION,
  OBSERVATION_API_VERSION,
  SAVE_FORMAT_VERSION,
  type AgentApiInfo,
} from './types';
import { cloneJson } from './action';

const PUBLIC_METHODS = [
  'getApiInfo', 'reset', 'getObservation', 'getLegalActions', 'step',
  'isGameOver', 'getResult', 'getRunArtifact',
] as const;

const CHECKPOINT_REASON_CODES: Readonly<Record<string, string>> = Object.freeze({
  invalid_checkpoint_tile: 'The destination is not an empty road tile that can contain a checkpoint.',
  invalid_checkpoint_branch: 'The destination does not belong to the selected road branch.',
  unknown_road_branch: 'The selected road branch does not exist in the current state.',
  checkpoint_prepared_post_limit_reached: 'The branch already has the maximum number of prepared Active and Standby posts.',
  unknown_operational_checkpoint: 'Relocation requires a known operational checkpoint.',
  unknown_activatable_checkpoint: 'Activation requires a known Standby or Dormant checkpoint on the selected branch.',
  checkpoint_same_position: 'Relocation must select a different road tile.',
  checkpoint_wrong_branch: 'A checkpoint can only relocate within its current branch.',
  checkpoint_infection_blocked: 'The checkpoint being moved or activated is infected and cannot change administrative role.',
  checkpoint_branch_action_limit: 'This branch already built, relocated, or activated a checkpoint this turn.',
  checkpoint_abandoned_forward_block: 'An infected ruined or abandoned site prevents placement at the same distance or farther from the capital.',
  checkpoint_supply_zombie_blocked: 'A player-visible Zombie is inside the candidate supply area.',
  insufficient_civilian_goods: 'The current Civilian Goods stock cannot pay the checkpoint construction cost.',
  action_limit: 'The global action limit for this turn has been reached.',
  wrong_phase: 'Checkpoint actions are only available during the player phase.',
  game_over: 'No checkpoint action is available after Game Over.',
});

export function createAgentApiInfo(
  config: Readonly<GameConfig>,
  buildId: string,
  bridgeApiVersion = BRIDGE_API_VERSION,
): AgentApiInfo {
  const policies = config.refugees.policies;
  return cloneJson({
    appVersion: APP_VERSION,
    gameRulesVersion: GAME_RULES_VERSION,
    saveFormatVersion: SAVE_FORMAT_VERSION,
    artifactSchemaVersion: ARTIFACT_SCHEMA_VERSION,
    agentApiVersion: AGENT_API_VERSION,
    observationApiVersion: OBSERVATION_API_VERSION,
    bridgeApiVersion,
    buildId,
    methods: [...PUBLIC_METHODS],
    methodSchemas: {
      getApiInfo: { arguments: 'none', returns: 'AgentApiInfo', description: 'Returns versions, public methods, fair-play boundaries, and static rules.' },
      reset: { arguments: 'AgentResetOptions? { seed?, configOverrides?, agent?: { id } }', returns: 'AgentObservation', description: 'Replaces the in-memory Agent session.' },
      getObservation: { arguments: 'none', returns: `AgentObservation ${OBSERVATION_API_VERSION}`, description: 'Returns a deterministic JSON copy of current public information, including Fuel previews, constructible candidates, strategic forecast, visibility, checkpoint candidates, Horde status, and Victory progress.' },
      getLegalActions: { arguments: 'none', returns: 'GameAction[]', description: 'Returns deterministic currently legal atomic actions.' },
      step: { arguments: 'one GameAction from getLegalActions()', returns: 'AgentStepResult', description: 'Validates and applies exactly one action through GameEngine.' },
      isGameOver: { arguments: 'none', returns: 'boolean', description: 'Reports whether the Agent session ended.' },
      getResult: { arguments: 'none', returns: 'AgentGameResult|null', description: 'Returns the public result when the game has ended.' },
      getRunArtifact: { arguments: 'none', returns: `AgentPublicRunArtifact ${ARTIFACT_SCHEMA_VERSION}`, description: 'Returns an in-memory public play trace without verification-only fields or exact Noise radii.' },
    },
    recommendedCallOrder: [...PUBLIC_METHODS],
    publicInformation: [
      'Use getObservation() for current public facts and getLegalActions() for currently legal operations.',
      'Call step() with one listed action at a time until isGameOver() is true.',
      'All returned values are detached JSON-compatible copies.',
      'Map terrain, roads, facility/checkpoint overlays, supply, Horde warning facts, and Victory progress are public.',
      'Checkpoint observations identify Active, Standby, Dormant, Remnant, Ruined, and Abandoned posts; branch policy belongs to the road branch.',
      'checkpointPositionCandidates contains every road tile or post with the Core-derived legal flag and first ActionError reason code.',
      'Human Units publish current/max Fuel, only legal Move Fuel costs, post-Move Fuel, and same-EndTurn refill demand/allocation.',
      'Facilities publish actual population and separate zombieTargetValue; Wind is a target value 5 but has no civilian population.',
      'strategicForecast is the Core projection for resource dependencies, Guaranteed Defeat, and Checkpoint Queue Pressure.',
      'Combat noise exposes only center, unit type, and public noise class. Both human unit types are Medium in the standard rules.',
      'The enemy list contains only currently visible normal Zombies and Horde Zombies; hidden enemies are omitted.',
    ],
    prohibited: [
      'GameState, PRNG state, future random outcomes, hidden enemy positions/counts, and unspawned Horde size are not public.',
      'Zombie Current Target, Inherited Target, Target Reason, hidden Spawn coordinates, and hidden enemy history are not public.',
      'Zombie Noise Target, exact Noise Radius, and affected hidden Zombie IDs or counts are not public.',
      'Checkpoint candidates never reveal blocker unit IDs; hidden enemies do not block a candidate or change its reason code.',
      'Constructible candidates and actions use only visible Zombies. Hidden Zombies never make an otherwise legal Build candidate illegal.',
      'LoadSnapshot, StartNewGame, SuppressInfection, arbitrary code, files, saves, localStorage, network, and Batch execution are not public actions.',
      'Do not infer or request private chain-of-thought; concise action reasons are sufficient.',
    ],
    rules: {
      recovery: {
        combatRate: config.naturalRecovery.combatRate,
        restRate: config.naturalRecovery.restRate,
        rounding: config.naturalRecovery.rounding,
        timing: 'nextPlayerTurnStart',
        supplyRequiredAtRecovery: true,
        combatActivities: ['attack', 'counterattack', 'interception', 'automatic_infection_suppression'],
        restActivities: ['move_only', 'wait', 'move_then_wait', 'no_action'],
      },
      infection: {
        stationedUnitsContainSpread: true,
        automaticSuppressionTiming: 'infectionPhaseAfterEndTurn',
        policeSuppression: config.infection.policeSuppression,
        nationalGuardSuppression: config.infection.nationalGuardSuppression,
        nationalGuardCivilianDamageFormula: `ceil(suppressionPower * ${config.infection.nationalGuardCivilianDamageRate})`,
      },
      ranges: {
        police: { baseRange: config.units.police.range },
        nationalGuard: { baseRange: config.units.nationalGuard.range },
        zombie: { baseRange: config.units.zombie.range },
        hordeZombie: { baseRange: config.units.hordeZombie.range },
        nationalGuardMilitarySupplyShortageRange: Math.min(1, config.units.nationalGuard.range),
      },
      terrain: {
        movementCost: cloneJson(config.terrain.movementCost),
        damageMultiplier: cloneJson(config.terrain.damageMultiplier),
        roadAndUrbanMovementCost: 1,
        defenseRounding: 'ceil',
        minimumDamage: 1,
      },
      vision: {
        unitVision: Object.fromEntries(
          Object.entries(config.units).map(([type, unit]) => [type, unit.vision]),
        ) as AgentApiInfo['rules']['vision']['unitVision'],
        capital: config.checkpoint.initialSupplyRadius,
        ownedFacility: config.vision.ownedFacility,
        operationalCheckpoint: config.vision.operationalCheckpoint,
        distance: 'hex',
        terrainBlocks: false,
        sources: ['human units', 'capital', 'owned non-fallen facilities', 'active checkpoints'],
      },
      fogOfWar: {
        enemyVisibility: 'visible_only',
        mapTerrainAlwaysKnown: true,
        hiddenEnemyPositionPublic: false,
        hiddenEnemyTargetPublic: false,
        hiddenEnemySpawnCoordinatePublic: false,
        hiddenEnemyCountPublic: false,
      },
      horde: {
        cycle: config.horde.cycle,
        periodicInitial: cloneJson(config.horde.periodicInitial),
        periodicIncrement: cloneJson(config.horde.periodicIncrement),
        warningStartTurn: config.horde.warningStartTurn,
        spawnOnlyBeforeFinalTurn: config.horde.spawnOnlyBeforeFinalTurn,
        finalHordeTurn: config.finalHordeTurn,
        finalComposition: cloneJson(config.horde.finalComposition),
      },
      victory: {
        requiresFinalHorde: true,
        progressFields: ['finalHordeDefeated', 'suppliedAreaZombieClear', 'suppliedAreaInfectionClear'],
        defeatPrecedesVictory: true,
      },
      checkpointPolicies: {
        passThrough: {
          turns: policies.passThrough.turns,
          acceptanceRate: policies.passThrough.workerRate,
          infectionBatchRate: policies.passThrough.infectionRate,
          infectedPopulationRate: policies.passThrough.infectionPopulationRate,
        },
        normal: {
          turns: policies.normal.turns,
          acceptanceRate: policies.normal.workerRate,
          infectionBatchRate: policies.normal.infectionRate,
          infectedPopulationRate: policies.normal.infectionPopulationRate,
        },
        strict: {
          turns: policies.strict.turns,
          acceptanceRate: policies.strict.workerRate,
          infectionBatchRate: policies.strict.infectionRate,
          infectedPopulationRate: policies.strict.infectionPopulationRate,
        },
      },
      checkpointPositionCandidates: {
        observationField: 'checkpointPositionCandidates',
        schema: {
          actionType: 'BuildCheckpoint | RelocateCheckpoint | ActivateCheckpoint',
          branchId: 'string',
          checkpointId: 'string (RelocateCheckpoint / ActivateCheckpoint; omitted for BuildCheckpoint)',
          position: '{ q: number; r: number }',
          legal: 'boolean',
          reasonCode: 'ActionError.code | null',
        },
        ordering: 'branch_id_then_branch_road_tile_order',
        includesIllegalCandidates: true,
        reasonCodes: cloneJson(CHECKPOINT_REASON_CODES),
        fairPlay: {
          hiddenEnemiesBlock: false,
          visibleEnemiesCanBlock: true,
          blockerUnitIdsPublic: false,
          prngStatePublic: false,
          futureRandomOutcomesPublic: false,
        },
      },
      checkpoint: {
        roles: ['active', 'standby', 'dormant', 'remnant', 'ruined', 'abandoned'],
        activePerBranchLimit: 1,
        preparedPostLimit: config.checkpoint.maxPreparedPostsPerDirection,
        policyOwner: 'road_branch',
        fallbackPriority: ['capital_side_standby', 'capital_side_dormant'],
        standbyProvidesArrivalSupplyVision: false,
        dormantProvidesArrivalSupplyVision: false,
      },
      unitFuel: {
        movementByType: {
          police: config.units.police.movement,
          nationalGuard: config.units.nationalGuard.movement,
        },
        maxFuelByType: {
          police: config.units.police.maxFuel,
          nationalGuard: config.units.nationalGuard.maxFuel,
        },
        fuelCostFormulaByType: {
          police: 'distance 0: 0; 1..5: 1; >=6: 1 + (distance - 5)',
          nationalGuard: 'distance 0: 0; 1..5: 1; >=6: 1 + 2 * (distance - 5)',
        },
        refuelTiming: 'after_power_before_production',
        refuelRequiresSupply: true,
        shortageAllocation: 'unit_id_ascending_round_robin',
      },
      constructibleFacilities: {
        types: ['simpleFarm', 'civilianDroneBase'],
        limitFormula: 'ceil(roadBranchCount / constructibleFacility.limitPerTypeDivisor)',
        buildConditions: [
          'inside_player_supply',
          'plain_base_terrain',
          'no_road_urban_or_horde_entrance',
          'no_facility_checkpoint_player_unit_or_visible_zombie',
          'per_type_limit_resources_and_action_budget',
        ],
        costs: {
          simpleFarm: config.facilities.simpleFarm.buildCivilianGoods,
          civilianDroneBase: config.facilities.civilianDroneBase.buildCivilianGoods,
        },
        stateTransitions: [
          'build_turn: building_empty_no_power_or_vision',
          'next_player_turn: operational',
          'empty_zombie_occupation: disabled',
          'human_recapture: recovering',
          'next_player_turn_after_recovery: operational_empty',
        ],
        simpleFarm: {
          workerCapacity: config.facilities.simpleFarm.workerCapacity,
          requiredPower: config.facilities.simpleFarm.production.powerCapacity,
          foodPerWorker: config.facilities.simpleFarm.production.outputs.food ?? 0,
        },
        civilianDroneBase: {
          workerCapacity: config.facilities.civilianDroneBase.workerCapacity,
          requiredPower: config.facilities.civilianDroneBase.production.powerCapacity,
          visionPerWorker: 2,
        },
        windPowerPlant: {
          fixedPower: config.facilities.windPowerPlant.production.fixedPowerGeneration,
          vision: config.facilities.windPowerPlant.visionRadius,
          zombieTargetValue: config.facilities.windPowerPlant.zombieTargetValue,
          supplySource: false,
        },
      },
      strategicForecast: {
        observationField: 'strategicForecast',
        resources: ['food', 'civilianGoods', 'militaryGoods', 'fuel', 'electricity'],
        guaranteedDefeat: ['guaranteed', 'causeResource', 'foodShortage', 'civilianGoodsShortage', 'projectedHealthyCivilians', 'defeatReason'],
        queuePressureThresholds: {
          none: 'queuePeople == 0',
          low: '0 < queuePeople <= screeningCapacity',
          medium: 'screeningCapacity < queuePeople <= screeningCapacity * 2',
          high: 'queuePeople > screeningCapacity * 2',
        },
      },
      noise: {
        classes: ['small', 'medium', 'large', 'extraLarge'],
        policeClass: config.noise.publicClass.police,
        nationalGuardClass: config.noise.publicClass.nationalGuard,
        distance: 'hex',
        terrainAttenuation: false,
        normalZombieAffected: true,
        hordeZombieAffected: false,
        targetPriority: ['visible_population', 'inherited_horde', 'noise', 'idle'],
      },
      production: {
        workerCapacityByFacilityType: Object.fromEntries(
          Object.entries(config.facilities).map(([type, facility]) => [type, facility.workerCapacity]),
        ) as AgentApiInfo['rules']['production']['workerCapacityByFacilityType'],
        powerPlantsGenerateCapacityPerWorker: config.facilities.powerPlant.production.powerGeneration,
        poweredFacilitiesConsumeFixedCapacityWhenOperating: true,
        fuelPerFiveElectricity: 1,
        facilityPowerUnit: 5,
        industrialPoweredMultiplier: 2,
        industrialUnpoweredMultiplier: 1,
        unpoweredCityCivilianGoodsOutputIsZero: true,
        sameTurnProductionCanCoverMaintenance: true,
        sameTurnProductionCanCoverProductionInputs: false,
        sameTurnCivilianGoodsCannotDirectlyFeedMilitaryFactories: true,
        civilianProductionCanReleaseTurnStartStockFromMaintenanceReservation: true,
        powerAllocationOrder: ['capital_and_cities', 'simple_farm', 'permanent_farm_and_civilian_factory', 'input_ready_military_factory', 'civilian_drone_base'],
      },
    },
    minimalExample: [
      'const game = window.NLTH; // Node: createAgentGame()',
      'const info = game.getApiInfo();',
      "let observation = game.reset({ seed: 1, agent: { id: 'example' } });",
      'while (!game.isGameOver()) {',
      '  const legal = game.getLegalActions();',
      '  if (legal.length === 0) break;',
      '  observation = game.step(legal[0]).observation;',
      '}',
      'const artifact = game.getRunArtifact();',
    ].join('\n'),
  } as AgentApiInfo);
}
