/** Current shared explanations for the aviation update. */
export const RULES_V165 = {
  ja: {
    objectives: '原発と空軍基地の初回確保期限はTurn10の行動終了まで。原発は健康生存者の有無を問わず特殊部隊が合流し、未確保ならTurn11にPack Zombieが出現します。空軍基地は期限内・初回確保前に陥落なし・健康生存者1人以上で特殊部隊が合流。生存者0でも期限内確保なら期限超過のPackは発生しません。未確保の陥落はPack発生を確定し、期限超過と重複しません。配置できない援軍は空き地ができるまで待機します。',
    airBase: '空軍基地は陸軍基地と同じWorker迎撃・専用軍需品を持ち、兵士と多目的ヘリを生産できます。初回確保報酬は食料100・軍需品100。無料の兵士は合流しません。軍用ドローンと生産にはSupply・正常稼働・電力が必要です。',
    helicopter: '多目的ヘリは生涯1機（予約を含む）。人口2・民需品100・軍需品140・燃料500で1ターン生産。Recruit、HP100、軍需品40・燃料500を搭載して着陸状態で完成します。飛行中は移動50・視界10・射程2、地形と地上部隊を無視。1Hexごとに燃料5、飛行したままターン終了で燃料1と半径15の騒音。地上は移動0。確保・復旧・鎮圧・感染封じ込めはできません。',
    flight: '離陸・着陸自体は燃料と攻撃権を使いません。同ターンの離陸後は通常着陸不可、着陸後は離陸不可。攻撃後は移動不可ですが、離陸したターンでなければ着陸できます。飛行中は補給・自然回復・地形防御なし。着陸中は自発攻撃不可、反撃・迎撃は可能。どの攻撃も必要な全量の軍需品（距離0～1で2、距離2で4）が必要です。',
    transport: '着陸ヘリは隣接する歩兵1隊を輸送できます。歩兵の残り行動だけを消費し、当ターンの降機は不可。ヘリ燃料0なら搭乗時に歩兵の燃料を保存則に従って移します。降機は隣接する空き地上Hexへ。次のPlayerTurnまで自発行動不可、残った攻撃権で敵フェーズに反応できます。搭乗中は独立した視界・攻撃・補給・回復なし。人口と維持費は続きます。▲は飛行、▣は搭乗部隊あり。同Hexタブで地上と空中を選択します。',
    emergency: '燃料1～4でも次の1Hexへ進み、0になると即時に緊急着陸します。現在地の地上が使えなければ隣接6Hexの合法な着地点から抽選。着地点がなければ墜落し、機体・搭乗部隊・元Hexの敵を失います。元Hexの味方地上部隊は巻き込みません。水上（橋なし）では搭乗者も再アニメーションしません。Previewは実際の抽選先を明かしません。',
    drone: '軍用ドローンは任意のHexへ、空軍基地からのHex距離×燃料5で派遣できます（距離0は無料）。半径10を地形無視で5ターン可視化。Turn20ならTurn24まで有効でTurn25開始に終了。稼働中の重複派遣は不可。基地喪失後も視界は期限まで残ります。',
    enemies: '飛行ヘリを攻撃できる敵はHunter ZombieとPack Zombieだけです。他の敵はヘリ・搭乗者を目標にせず、騒音には反応します。飛行ヘリは砲撃・Gas爆発の被害対象外です。ヘリは再アニメーションせず、搭乗歩兵は通常の変異規則に従います。',
    economy: '仮設住宅の民需品生産は0（人口受入と維持費は継続）。正の施設電力容量は従来の2倍、軍需工場はWorker1人あたり民需品2→軍需品1。Wave特殊枠の重みはNormal40 / Police10 / Soldier10 / Riot5 / Hunter15 / Gas15 / Screamer5。HunterとGasに方向別上限はありません。',
    compatibility: 'v1.6.4以前のSave・Replay・Session・Checkpoint・Artifactは読み込み不可です。旧データは残し、v1.6.5で新規ゲームを開始してください。',
  },
  en: {
    objectives: 'First capture deadlines for the nuclear plant and Air Base are the end of Turn 10 actions. Nuclear capture awards Special Forces regardless of survivors; no capture causes a Pack Zombie on Turn 11. The Air Base reward requires timely first capture, no earlier fall, and at least one healthy survivor. Timely capture with zero survivors still avoids the deadline Pack. A pre-capture fall commits one Pack, without a duplicate at the deadline. Blocked reinforcements remain pending until placement is possible.',
    airBase: 'The Air Base shares Army Base worker interceptions and dedicated ammunition. It recruits Soldiers and one multipurpose helicopter. First capture gives 100 Food and 100 Military Goods, without a free Soldier. Drone launch and production require Supply, normal operation and power.',
    helicopter: 'One helicopter per game, including reservations. Cost: population 2, Civilian Goods 100, Military Goods 140, Fuel 500; one production turn. Arrives landed as Recruit with HP100, ammunition40 and Fuel500. Airborne movement50, vision10, range2; ignores terrain and ground units. Each Hex costs 5 Fuel; ending a turn airborne costs 1 Fuel and emits radius15 noise. Landed movement0. Cannot capture, recover, suppress or contain infection.',
    flight: 'Takeoff and landing consume no Fuel or attack charge. No normal landing on the takeoff turn, nor takeoff on the landing turn. Attacks stop movement but allow landing unless takeoff was this turn. Airborne units receive no supply, recovery or terrain protection. Landed aircraft may react but not attack voluntarily. Every attack requires full ammunition: 2 at distance0–1, 4 at distance2.',
    transport: 'A landed helicopter carries one adjacent infantry unit. Boarding consumes only infantry actions; no same-turn disembark. Boarding at zero helicopter Fuel transfers infantry Fuel without creating fuel. Disembark to an adjacent free ground Hex: no voluntary actions until next Player Turn, but enemy-phase reactions use remaining charges. Cargo has no separate vision, attack, supply or recovery; population and upkeep continue. ▲ means airborne, ▣ means cargo. Same-Hex tabs select ground and air units separately.',
    emergency: 'Fuel1–4 still permits the next Hex, then immediate emergency landing at zero. If current ground is unavailable, draw among legal adjacent Hexes. No landing place means a crash, losing the aircraft, cargo and enemies at the original Hex, without harming friendly ground units. Cargo does not reanimate over unbridged water. Preview never reveals the actual random landing.',
    drone: 'Launch to any Hex for distance from the Air Base × 5 national Fuel (zero distance is free). Terrain-ignoring radius10 vision lasts five turns: a Turn20 launch lasts through Turn24 and expires at Turn25 start. Only one active drone; base loss does not cancel existing vision.',
    enemies: 'Only Hunter and Pack Zombies can attack airborne helicopters. Other enemies ignore aircraft and cargo as targets but follow noise. Airborne helicopters ignore artillery and Gas blast damage. Helicopters never reanimate; cargo follows its normal conversion rules.',
    economy: 'Temporary Housing produces zero Civilian Goods; capacity and upkeep continue. Positive facility power capacities are doubled. Military Factories convert 2 Civilian Goods into 1 Military Good per worker. Wave slot weights: Normal40 / Police10 / Soldier10 / Riot5 / Hunter15 / Gas15 / Screamer5. Hunter and Gas have no per-direction cap.',
    compatibility: 'Save, Replay, Session, Checkpoint and Artifact data from v1.6.4 or earlier is rejected. Preserve old data and start a new v1.6.5 game.',
  },
} as const;
